### ISSUE TITLE
Cannot read property 'class' of undefined

### ISSUE THREAD

**Issue by osdevisnot** [picostyle/picostyle#23]
Not sure if this was reported and/or discussed before, but with latest hyperapp (0.14.0) and latest picostyle (0.1.5) I am noticing this error:

![image](https://user-images.githubusercontent.com/802242/31319181-83a53940-ac13-11e7-902d-b8d76c250f31.png)

Here is a codepen for repro - https://codepen.io/abhishekisnot/pen/XeENxo

I will try to get to this later, reporting here if anyone else gets to it earlier.

**Comment by JorgeBucaran** [comment]
@osdevisnot Hmm same as https://github.com/hyperapp/hyperapp/issues/402 and the issue is [here](https://github.com/picostyle/picostyle/blob/db6c16d42e548fb34128495ad691dfb853d64b4c/src/index.js#L48). It should be changed to `props` or use a different merging strategy. 

This is an easy fix. If you send us a PR I'd review it.

**Comment by morishitter** [comment]
@osdevisnot Good catch!
